tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"

brew "readline"
brew "sqlite"
brew "xz"
brew "awscli"
brew "libffi"
brew "pkg-config"
brew "gh"
brew "git"
brew "gnupg"
brew "graphviz"
brew "lapack"
brew "libxml2"
brew "libxmlsec1"
brew "node"
brew "nvm"
brew "openblas"
brew "openssl@3"
brew "postgresql", restart_service: true
brew "pyenv"
brew "pyenv-virtualenv"
brew "rabbitmq", restart_service: true
brew "redis", restart_service: true
brew "semgrep"
brew "yarn"
brew "zlib"
brew "zsh"
brew "heroku/brew/heroku"

cask "cleanshot"
cask "docker"
cask "insomnia"
cask "mongodb-compass"
cask "ngrok"
cask "postico"
cask "selfcontrol"
cask "spotify"
